channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=26.1.2
- pip:
  - mlflow==2.19.0
  - scikit-learn==1.9.0
  - numpy==1.26.4
  - pandas==2.2.3
  - dagshub
  - matplotlib
  - joblib
name: mlflow-env
